Add /opt/local dirs to libheif_build.py
carsales/pyheif pull request #38
Opened 2021-01-15 17:27 UTC by jiawen

This enables out of the box MacPorts builds.

Closes: https://github.com/carsales/pyheif/issues/32

2021-02-02 10:32 UTC, david-poirier-csn commented on libheif/libheif_build.py
> +    # dirs prefixed with "/opt/local" enable out of the box MacPorts builds.
Please remove this comment :)

2021-02-02 10:32 UTC, david-poirier-csn requested changes
Looks ok, just remove the comment pls

2021-02-03 22:03 UTC, jiawen commented
Done. Force pushed. PTAL.

Thanks.

2021-02-04 01:32 UTC, merged

2021-02-04 01:32 UTC, david-poirier-csn commented
Good stuff, thanks